/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProjectIdIndexRouteImport } from './routes/app/$projectId/index'
import { Route as AppProjectIdTerminalTerminalIdIndexRouteImport } from './routes/app/$projectId/terminal/$terminalId.index'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectIdIndexRoute = AppProjectIdIndexRouteImport.update({
  id: '/$projectId/',
  path: '/$projectId/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdTerminalTerminalIdIndexRoute =
  AppProjectIdTerminalTerminalIdIndexRouteImport.update({
    id: '/$projectId/terminal/$terminalId/',
    path: '/$projectId/terminal/$terminalId/',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$projectId/': typeof AppProjectIdIndexRoute
  '/app/$projectId/terminal/$terminalId/': typeof AppProjectIdTerminalTerminalIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$projectId': typeof AppProjectIdIndexRoute
  '/app/$projectId/terminal/$terminalId': typeof AppProjectIdTerminalTerminalIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$projectId/': typeof AppProjectIdIndexRoute
  '/app/$projectId/terminal/$terminalId/': typeof AppProjectIdTerminalTerminalIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/$projectId/'
    | '/app/$projectId/terminal/$terminalId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/app/$projectId' | '/app/$projectId/terminal/$terminalId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/$projectId/'
    | '/app/$projectId/terminal/$terminalId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$projectId/': {
      id: '/app/$projectId/'
      path: '/$projectId'
      fullPath: '/app/$projectId/'
      preLoaderRoute: typeof AppProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/terminal/$terminalId/': {
      id: '/app/$projectId/terminal/$terminalId/'
      path: '/$projectId/terminal/$terminalId'
      fullPath: '/app/$projectId/terminal/$terminalId/'
      preLoaderRoute: typeof AppProjectIdTerminalTerminalIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProjectIdIndexRoute: typeof AppProjectIdIndexRoute
  AppProjectIdTerminalTerminalIdIndexRoute: typeof AppProjectIdTerminalTerminalIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProjectIdIndexRoute: AppProjectIdIndexRoute,
  AppProjectIdTerminalTerminalIdIndexRoute:
    AppProjectIdTerminalTerminalIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
